version: "3.7"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    tty: true
    volumes:
      - ./:/opt/batch
      - batch_node_modules:/opt/batch/node_modules
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: password

  db:
    image: mysql:8.0
    command: >
      mysqld
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --skip-character-set-client-handshake
    volumes:
      - batch_db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password

volumes:
  batch_node_modules:
  batch_db_data:
