// Code generated by SQLBoiler 4.14.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Authors          string
	Hashtags         string
	MediaObjects     string
	SchemaMigrations string
	TweetObjects     string
	Vtubers          string
}{
	Authors:          "authors",
	Hashtags:         "hashtags",
	MediaObjects:     "media_objects",
	SchemaMigrations: "schema_migrations",
	TweetObjects:     "tweet_objects",
	Vtubers:          "vtubers",
}
